### ISSUE TITLE
Config Blues

### ISSUE THREAD

**Issue by gordonguthrie** [erldocs/erldocs#1]
Clicked through to the User Guide on:
http://erldocs.com/R16B02/common_test/common_test_app.html

*********Context************
This function is called after each test case, and can be used to clean up after init_per_testcase/2 and the test case. Any return value (besides {fail,Reason} and {save_config,SaveConfig}) is ignored. By returning {fail,Reason}, TestCase will be marked as failed (even though it was actually successful in the sense that it returned a value instead of terminating). For information on save_config, please see Dependencies between Test Cases and Suites in the User's Guide
********************************

Got a 404

http://erldocs.com/R16B02/common_test/dependencies_chapter.html#save_config

PS great to see Erldocs back...

**Comment by fenollp** [comment]
This is counting as the fix: https://github.com/erldocs/erldocs.com/commit/311b361fb0aa8913109da14e8be2f475d30bde97
