### ISSUE TITLE
Multiple clause specs are not properly handled

### ISSUE THREAD

**Issue by elbrujohalcon** [erldocs/erldocs#22]
Consider the differences on the `erlang:statistics/1` doc between [the official doc](http://www.erlang.org/doc/man/erlang.html#statistics-1) and [erldocs](http://erldocs.com/current/erts/erlang.html?i=0&search=erlang:stat#statistics/1) and how that's related to the [long multi-clause spec for that function](https://github.com/erlang/otp/blob/maint/erts/preloaded/src/erlang.erl#L2038-L2065).

**Comment by fenollp** [comment]
This looks like https://github.com/erldocs/erldocs/issues/11 is back!

I'll have a look when I find time, but it looks like the whole file does not get rendered properly (Fun/Arity everywhere) meaning something else is fishy…

**Comment by brucify** [comment]
This is related to https://github.com/erldocs/erldocs/issues/28

**Comment by fenollp** [comment]
Closing in favour of #28
