### ISSUE TITLE
Funny characters - windows 10, chrome

### ISSUE THREAD

**Issue by drozzy** [erldocs/erldocs#51]
Here is what I see in pretty much every code example:
![funnies](https://cloud.githubusercontent.com/assets/140710/13194465/3915fcb2-d761-11e5-93be-1abb889148a7.png)

**Comment by jesperes** [comment]
I've been annoyed by this for quite some time. The "funny characters" are unicode `U+FFFD`, "unicode replacement character (https://en.wikipedia.org/wiki/Specials_(Unicode_block)#Replacement_character), and occurs when the input doc xml uses constructs such as `&nbsp;` or `<c>...</c>`. Somewhere along the line, the conversion to HTML freaks out and insert a replacement char instead.

I'll dig around a bit and see if I can figure out a way to fix this.

**Comment by jesperes** [comment]
Made a PR which fixes this: https://github.com/erldocs/erldocs/pull/68
