### ISSUE TITLE
erlang/otp 22 docs not found in the erldocs.com, please update it.

### ISSUE THREAD

**Issue by getong** [erldocs/erldocs#69]

**Comment by kvelicka** [comment]
+1

Is the website still alive? Perhaps the maintainer(s) are looking for help to maintain the site?

**Comment by fenollp** [comment]
Good point Karl. Website is still alive! I should look into Github's Actions or at least some kind of cron-able CI so it can mostly have a life of its own.

**Comment by fenollp** [comment]
So I just manually generated an R22 version. 
Note this regression needs work though: https://github.com/erldocs/erldocs/issues/70
